name = "cf-speedtest-worker"
main = "build/index.js"
compatibility_date = "2026-01-24"

# Disable `workers.dev` domain
workers_dev = false

[observability]
enabled = true
head_sampling_rate = 1

[build]
command = "RUSTFLAGS=\"-Zfmt-debug=none -Zfmt-debug=none\" worker-build --profile release-wasm"
