name: build-image

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_REGISTRY: ghcr.io
  IMAGE_REGISTRY_USERNAME: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BUILD_PLATFORMS: linux/amd64,linux/arm64
  # See https://quay.io/repository/buildah/stable?tab=tags
  IMAGE_BUILDAH_VERSION: 1.43.2-immutable
  IMAGE_BUILDAH_DIGEST: 19ee6da290f77e63ab7f108a1b22e63d4c36cb827fba9f494982c5ceeba27019

jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases/tag/v7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Prepare buildah
        run: |
          podman build \
              --build-arg IMAGE_BUILDAH_VERSION="${IMAGE_BUILDAH_VERSION}" \
              --build-arg IMAGE_BUILDAH_DIGEST="${IMAGE_BUILDAH_DIGEST}" \
              -f Dockerfile.buildah \
              -t localhost/buildah/stable:tespeed

      - name: Build
        run: |
          podman run \
              --rm \
              --device /dev/fuse \
              --security-opt label=disable \
              -v "$PWD:/workspace" \
              -w /workspace \
              -e IMAGE_REGISTRY="${IMAGE_REGISTRY}" \
              -e IMAGE_NAME="${IMAGE_NAME}" \
              -e IMAGE_BUILD_PLATFORMS="${IMAGE_BUILD_PLATFORMS}" \
              -e IMAGE_REGISTRY_USERNAME="${IMAGE_REGISTRY_USERNAME}" \
              -e IMAGE_REGISTRY_PASSWORD="${IMAGE_REGISTRY_PASSWORD}" \
              --user=root \
              localhost/buildah/stable:tespeed \
              ./build.sh --push
